Imports System
Imports System.IO
Imports ProtoBuf
' This file was generated by a tool; you should avoid making direct changes.
' Consider using 'partial classes' to extend these types
' Input: my.proto

#Disable Warning BC40008, BC40055, IDE1006
<Global.ProtoBuf.ProtoContract()>
Partial Public Class Attributes
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name:="ground")>
    Public Property GroundValue As Ground

    <Global.ProtoBuf.ProtoMember(2)>
    Public Property groundBorder As Boolean
        Get
            Return __pbn__groundBorder.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__groundBorder = value
        End Set
    End Property
    Public Function ShouldSerializegroundBorder() As Boolean
        Return Not (__pbn__groundBorder Is Nothing)
    End Function
    Public Sub ResetgroundBorder()
        __pbn__groundBorder = Nothing
    End Sub
    Private __pbn__groundBorder As Boolean?

    <Global.ProtoBuf.ProtoMember(3, Name:="bottom")>
    Public Property Bottom As Boolean
        Get
            Return __pbn__Bottom.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Bottom = value
        End Set
    End Property
    Public Function ShouldSerializeBottom() As Boolean
        Return Not (__pbn__Bottom Is Nothing)
    End Function
    Public Sub ResetBottom()
        __pbn__Bottom = Nothing
    End Sub
    Private __pbn__Bottom As Boolean?

    <Global.ProtoBuf.ProtoMember(4, Name:="top")>
    Public Property Top As Boolean
        Get
            Return __pbn__Top.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Top = value
        End Set
    End Property
    Public Function ShouldSerializeTop() As Boolean
        Return Not (__pbn__Top Is Nothing)
    End Function
    Public Sub ResetTop()
        __pbn__Top = Nothing
    End Sub
    Private __pbn__Top As Boolean?

    <Global.ProtoBuf.ProtoMember(5, Name:="container")>
    Public Property Container As Boolean
        Get
            Return __pbn__Container.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Container = value
        End Set
    End Property
    Public Function ShouldSerializeContainer() As Boolean
        Return Not (__pbn__Container Is Nothing)
    End Function
    Public Sub ResetContainer()
        __pbn__Container = Nothing
    End Sub
    Private __pbn__Container As Boolean?

    <Global.ProtoBuf.ProtoMember(6, Name:="stackable")>
    Public Property Stackable As Boolean
        Get
            Return __pbn__Stackable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Stackable = value
        End Set
    End Property
    Public Function ShouldSerializeStackable() As Boolean
        Return Not (__pbn__Stackable Is Nothing)
    End Function
    Public Sub ResetStackable()
        __pbn__Stackable = Nothing
    End Sub
    Private __pbn__Stackable As Boolean?

    <Global.ProtoBuf.ProtoMember(7, Name:="use")>
    Public Property Use As Boolean
        Get
            Return __pbn__Use.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Use = value
        End Set
    End Property
    Public Function ShouldSerializeUse() As Boolean
        Return Not (__pbn__Use Is Nothing)
    End Function
    Public Sub ResetUse()
        __pbn__Use = Nothing
    End Sub
    Private __pbn__Use As Boolean?

    <Global.ProtoBuf.ProtoMember(8)>
    Public Property forceUse As Boolean
        Get
            Return __pbn__forceUse.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__forceUse = value
        End Set
    End Property
    Public Function ShouldSerializeforceUse() As Boolean
        Return Not (__pbn__forceUse Is Nothing)
    End Function
    Public Sub ResetforceUse()
        __pbn__forceUse = Nothing
    End Sub
    Private __pbn__forceUse As Boolean?

    <Global.ProtoBuf.ProtoMember(9)>
    Public Property multiUse As Boolean
        Get
            Return __pbn__multiUse.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__multiUse = value
        End Set
    End Property
    Public Function ShouldSerializemultiUse() As Boolean
        Return Not (__pbn__multiUse Is Nothing)
    End Function
    Public Sub ResetmultiUse()
        __pbn__multiUse = Nothing
    End Sub
    Private __pbn__multiUse As Boolean?

    <Global.ProtoBuf.ProtoMember(10, Name:="writable")>
    Public Property WritableValue As Writable

    <Global.ProtoBuf.ProtoMember(11, Name:="writableOnce")>
    Public Property writableOnceValue As WritableOnce

    <Global.ProtoBuf.ProtoMember(12, Name:="splash")>
    Public Property Splash As Boolean
        Get
            Return __pbn__Splash.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Splash = value
        End Set
    End Property
    Public Function ShouldSerializeSplash() As Boolean
        Return Not (__pbn__Splash Is Nothing)
    End Function
    Public Sub ResetSplash()
        __pbn__Splash = Nothing
    End Sub
    Private __pbn__Splash As Boolean?

    <Global.ProtoBuf.ProtoMember(13, Name:="unwalkable")>
    Public Property Unwalkable As Boolean
        Get
            Return __pbn__Unwalkable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Unwalkable = value
        End Set
    End Property
    Public Function ShouldSerializeUnwalkable() As Boolean
        Return Not (__pbn__Unwalkable Is Nothing)
    End Function
    Public Sub ResetUnwalkable()
        __pbn__Unwalkable = Nothing
    End Sub
    Private __pbn__Unwalkable As Boolean?

    <Global.ProtoBuf.ProtoMember(14, Name:="unmovable")>
    Public Property Unmovable As Boolean
        Get
            Return __pbn__Unmovable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Unmovable = value
        End Set
    End Property
    Public Function ShouldSerializeUnmovable() As Boolean
        Return Not (__pbn__Unmovable Is Nothing)
    End Function
    Public Sub ResetUnmovable()
        __pbn__Unmovable = Nothing
    End Sub
    Private __pbn__Unmovable As Boolean?

    <Global.ProtoBuf.ProtoMember(15, Name:="unsight")>
    Public Property Unsight As Boolean
        Get
            Return __pbn__Unsight.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Unsight = value
        End Set
    End Property
    Public Function ShouldSerializeUnsight() As Boolean
        Return Not (__pbn__Unsight Is Nothing)
    End Function
    Public Sub ResetUnsight()
        __pbn__Unsight = Nothing
    End Sub
    Private __pbn__Unsight As Boolean?

    <Global.ProtoBuf.ProtoMember(16)>
    Public Property blockPath As Boolean
        Get
            Return __pbn__blockPath.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__blockPath = value
        End Set
    End Property
    Public Function ShouldSerializeblockPath() As Boolean
        Return Not (__pbn__blockPath Is Nothing)
    End Function
    Public Sub ResetblockPath()
        __pbn__blockPath = Nothing
    End Sub
    Private __pbn__blockPath As Boolean?

    <Global.ProtoBuf.ProtoMember(17)>
    Public Property noMoveAnimation As Boolean
        Get
            Return __pbn__noMoveAnimation.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__noMoveAnimation = value
        End Set
    End Property
    Public Function ShouldSerializenoMoveAnimation() As Boolean
        Return Not (__pbn__noMoveAnimation Is Nothing)
    End Function
    Public Sub ResetnoMoveAnimation()
        __pbn__noMoveAnimation = Nothing
    End Sub
    Private __pbn__noMoveAnimation As Boolean?

    <Global.ProtoBuf.ProtoMember(18, Name:="pickupable")>
    Public Property Pickupable As Boolean
        Get
            Return __pbn__Pickupable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Pickupable = value
        End Set
    End Property
    Public Function ShouldSerializePickupable() As Boolean
        Return Not (__pbn__Pickupable Is Nothing)
    End Function
    Public Sub ResetPickupable()
        __pbn__Pickupable = Nothing
    End Sub
    Private __pbn__Pickupable As Boolean?

    <Global.ProtoBuf.ProtoMember(19)>
    Public Property fluidContainer As Boolean
        Get
            Return __pbn__fluidContainer.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__fluidContainer = value
        End Set
    End Property
    Public Function ShouldSerializefluidContainer() As Boolean
        Return Not (__pbn__fluidContainer Is Nothing)
    End Function
    Public Sub ResetfluidContainer()
        __pbn__fluidContainer = Nothing
    End Sub
    Private __pbn__fluidContainer As Boolean?

    <Global.ProtoBuf.ProtoMember(20, Name:="hangable")>
    Public Property Hangable As Boolean
        Get
            Return __pbn__Hangable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Hangable = value
        End Set
    End Property
    Public Function ShouldSerializeHangable() As Boolean
        Return Not (__pbn__Hangable Is Nothing)
    End Function
    Public Sub ResetHangable()
        __pbn__Hangable = Nothing
    End Sub
    Private __pbn__Hangable As Boolean?

    <Global.ProtoBuf.ProtoMember(21, Name:="hook")>
    Public Property HookValue As Hook

    <Global.ProtoBuf.ProtoMember(22, Name:="rotatable")>
    Public Property Rotatable As Boolean
        Get
            Return __pbn__Rotatable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Rotatable = value
        End Set
    End Property
    Public Function ShouldSerializeRotatable() As Boolean
        Return Not (__pbn__Rotatable Is Nothing)
    End Function
    Public Sub ResetRotatable()
        __pbn__Rotatable = Nothing
    End Sub
    Private __pbn__Rotatable As Boolean?

    <Global.ProtoBuf.ProtoMember(23, Name:="light")>
    Public Property LightValue As Light

    <Global.ProtoBuf.ProtoMember(24)>
    Public Property dontHide As Boolean
        Get
            Return __pbn__dontHide.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__dontHide = value
        End Set
    End Property
    Public Function ShouldSerializedontHide() As Boolean
        Return Not (__pbn__dontHide Is Nothing)
    End Function
    Public Sub ResetdontHide()
        __pbn__dontHide = Nothing
    End Sub
    Private __pbn__dontHide As Boolean?

    <Global.ProtoBuf.ProtoMember(25, Name:="translucent")>
    Public Property Translucent As Boolean
        Get
            Return __pbn__Translucent.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Translucent = value
        End Set
    End Property
    Public Function ShouldSerializeTranslucent() As Boolean
        Return Not (__pbn__Translucent Is Nothing)
    End Function
    Public Sub ResetTranslucent()
        __pbn__Translucent = Nothing
    End Sub
    Private __pbn__Translucent As Boolean?

    <Global.ProtoBuf.ProtoMember(26, Name:="elevation")>
    Public Property ElevationValue As Elevation

    <Global.ProtoBuf.ProtoMember(27, Name:="height")>
    Public Property HeightValue As Height

    <Global.ProtoBuf.ProtoMember(28)>
    Public Property lyingObject As Boolean
        Get
            Return __pbn__lyingObject.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__lyingObject = value
        End Set
    End Property
    Public Function ShouldSerializelyingObject() As Boolean
        Return Not (__pbn__lyingObject Is Nothing)
    End Function
    Public Sub ResetlyingObject()
        __pbn__lyingObject = Nothing
    End Sub
    Private __pbn__lyingObject As Boolean?

    <Global.ProtoBuf.ProtoMember(29)>
    Public Property alwaysAnimated As Boolean
        Get
            Return __pbn__alwaysAnimated.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__alwaysAnimated = value
        End Set
    End Property
    Public Function ShouldSerializealwaysAnimated() As Boolean
        Return Not (__pbn__alwaysAnimated Is Nothing)
    End Function
    Public Sub ResetalwaysAnimated()
        __pbn__alwaysAnimated = Nothing
    End Sub
    Private __pbn__alwaysAnimated As Boolean?

    <Global.ProtoBuf.ProtoMember(30)>
    Public Property minimapColor As Minimap

    <Global.ProtoBuf.ProtoMember(31)>
    Public Property lenshelpType As LensHelp

    <Global.ProtoBuf.ProtoMember(32)>
    Public Property fullGround As Boolean
        Get
            Return __pbn__fullGround.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__fullGround = value
        End Set
    End Property
    Public Function ShouldSerializefullGround() As Boolean
        Return Not (__pbn__fullGround Is Nothing)
    End Function
    Public Sub ResetfullGround()
        __pbn__fullGround = Nothing
    End Sub
    Private __pbn__fullGround As Boolean?

    <Global.ProtoBuf.ProtoMember(33)>
    Public Property ignoreLook As Boolean
        Get
            Return __pbn__ignoreLook.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__ignoreLook = value
        End Set
    End Property
    Public Function ShouldSerializeignoreLook() As Boolean
        Return Not (__pbn__ignoreLook Is Nothing)
    End Function
    Public Sub ResetignoreLook()
        __pbn__ignoreLook = Nothing
    End Sub
    Private __pbn__ignoreLook As Boolean?

    <Global.ProtoBuf.ProtoMember(34, Name:="cloth")>
    Public Property Cloth As Clothes

    <Global.ProtoBuf.ProtoMember(35, Name:="defaultAction")>
    Public Property defaultActionValue As DefaultAction

    <Global.ProtoBuf.ProtoMember(36)>
    Public Property marketData As Market

    <Global.ProtoBuf.ProtoMember(37, Name:="wrappable")>
    Public Property Wrappable As Boolean
        Get
            Return __pbn__Wrappable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Wrappable = value
        End Set
    End Property
    Public Function ShouldSerializeWrappable() As Boolean
        Return Not (__pbn__Wrappable Is Nothing)
    End Function
    Public Sub ResetWrappable()
        __pbn__Wrappable = Nothing
    End Sub
    Private __pbn__Wrappable As Boolean?

    <Global.ProtoBuf.ProtoMember(38, Name:="unwrappable")>
    Public Property Unwrappable As Boolean
        Get
            Return __pbn__Unwrappable.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Unwrappable = value
        End Set
    End Property
    Public Function ShouldSerializeUnwrappable() As Boolean
        Return Not (__pbn__Unwrappable Is Nothing)
    End Function
    Public Sub ResetUnwrappable()
        __pbn__Unwrappable = Nothing
    End Sub
    Private __pbn__Unwrappable As Boolean?

    <Global.ProtoBuf.ProtoMember(39, Name:="topeffect")>
    Public Property Topeffect As Boolean
        Get
            Return __pbn__Topeffect.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Topeffect = value
        End Set
    End Property
    Public Function ShouldSerializeTopeffect() As Boolean
        Return Not (__pbn__Topeffect Is Nothing)
    End Function
    Public Sub ResetTopeffect()
        __pbn__Topeffect = Nothing
    End Sub
    Private __pbn__Topeffect As Boolean?

    <Global.ProtoBuf.ProtoMember(40, Name:="npcTradeData")>
    Public ReadOnly Property npcTradeDatas As New Global.System.Collections.Generic.List(Of AppearanceFlagNPC)

    <Global.ProtoBuf.ProtoMember(41)>
    Public Property changedToExpire As AppearanceFlagChangedToExpire

    <Global.ProtoBuf.ProtoMember(42, Name:="corpse")>
    Public Property Corpse As Boolean
        Get
            Return __pbn__Corpse.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__Corpse = value
        End Set
    End Property
    Public Function ShouldSerializeCorpse() As Boolean
        Return Not (__pbn__Corpse Is Nothing)
    End Function
    Public Sub ResetCorpse()
        __pbn__Corpse = Nothing
    End Sub
    Private __pbn__Corpse As Boolean?

    <Global.ProtoBuf.ProtoMember(43)>
    Public Property playeCorpse As Boolean
        Get
            Return __pbn__playeCorpse.GetValueOrDefault()
        End Get
        Set(ByVal value As Boolean)
            __pbn__playeCorpse = value
        End Set
    End Property
    Public Function ShouldSerializeplayeCorpse() As Boolean
        Return Not (__pbn__playeCorpse Is Nothing)
    End Function
    Public Sub ResetplayeCorpse()
        __pbn__playeCorpse = Nothing
    End Sub
    Private __pbn__playeCorpse As Boolean?

    <Global.ProtoBuf.ProtoMember(44)>
    Public Property cyclopediaItem As AppearanceFlagCyclopedia

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Ground
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="speed", IsRequired:=True)>
        Public Property Speed As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Writable
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="length", IsRequired:=True)>
        Public Property Length As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class WritableOnce
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="length", IsRequired:=True)>
        Public Property Length As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Hook
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="direction", IsRequired:=True)>
        Public Property Direction As HookType = HookType.HookSouth

        <Global.ProtoBuf.ProtoContract(Name:="HOOK_TYPE")>
        Public Enum HookType
            <Global.ProtoBuf.ProtoEnum(Name:="HOOK_SOUTH")>
            HookSouth = 1
            <Global.ProtoBuf.ProtoEnum(Name:="HOOK_EAST")>
            HookEast = 2
        End Enum

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Light
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="brightness", IsRequired:=True)>
        Public Property Brightness As UInteger

        <Global.ProtoBuf.ProtoMember(2, Name:="color", IsRequired:=True)>
        Public Property Color As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Elevation
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="x", IsRequired:=True)>
        Public Property X As UInteger

        <Global.ProtoBuf.ProtoMember(2, Name:="y", IsRequired:=True)>
        Public Property Y As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Height
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="elevation", IsRequired:=True)>
        Public Property Elevation As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Minimap
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="color", IsRequired:=True)>
        Public Property Color As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class LensHelp
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="id", IsRequired:=True)>
        Public Property Id As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Clothes
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="slot", IsRequired:=True)>
        Public Property Slot As UInteger

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class DefaultAction
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="action", IsRequired:=True)>
        Public Property Action As PlayerAction

        <Global.ProtoBuf.ProtoContract(Name:="PLAYER_ACTION")>
        Public Enum PlayerAction
            <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_NONE")>
            PlayerActionNone = 0
            <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_LOOK")>
            PlayerActionLook = 1
            <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_USE")>
            PlayerActionUse = 2
            <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_OPEN")>
            PlayerActionOpen = 3
            <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_AUTOWALK_HIGHLIGHT")>
            PlayerActionAutowalkHighlight = 4
        End Enum

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class Market
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="category")>
        Public Property Category As UInteger
            Get
                Return __pbn__Category.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__Category = value
            End Set
        End Property
        Public Function ShouldSerializeCategory() As Boolean
            Return Not (__pbn__Category Is Nothing)
        End Function
        Public Sub ResetCategory()
            __pbn__Category = Nothing
        End Sub
        Private __pbn__Category As UInteger?

        <Global.ProtoBuf.ProtoMember(2)>
        Public Property tradeAs As UInteger
            Get
                Return __pbn__tradeAs.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__tradeAs = value
            End Set
        End Property
        Public Function ShouldSerializetradeAs() As Boolean
            Return Not (__pbn__tradeAs Is Nothing)
        End Function
        Public Sub ResettradeAs()
            __pbn__tradeAs = Nothing
        End Sub
        Private __pbn__tradeAs As UInteger?

        <Global.ProtoBuf.ProtoMember(3, Name:="show_as_object_id")>
        Public Property ShowAsObjectId As UInteger
            Get
                Return __pbn__ShowAsObjectId.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__ShowAsObjectId = value
            End Set
        End Property
        Public Function ShouldSerializeShowAsObjectId() As Boolean
            Return Not (__pbn__ShowAsObjectId Is Nothing)
        End Function
        Public Sub ResetShowAsObjectId()
            __pbn__ShowAsObjectId = Nothing
        End Sub
        Private __pbn__ShowAsObjectId As UInteger?

        <Global.ProtoBuf.ProtoMember(5, Name:="vocation")>
        Public Property Vocations As UInteger()

        <Global.ProtoBuf.ProtoMember(6, Name:="level")>
        Public Property Level As UInteger
            Get
                Return __pbn__Level.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__Level = value
            End Set
        End Property
        Public Function ShouldSerializeLevel() As Boolean
            Return Not (__pbn__Level Is Nothing)
        End Function
        Public Sub ResetLevel()
            __pbn__Level = Nothing
        End Sub
        Private __pbn__Level As UInteger?

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class AppearanceFlagNPC
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, Name:="name")>
        <Global.System.ComponentModel.DefaultValue("")>
        Public Property Name As String
            Get
                Return If(__pbn__Name, "")
            End Get
            Set(ByVal value As String)
                __pbn__Name = value
            End Set
        End Property
        Public Function ShouldSerializeName() As Boolean
            Return Not (__pbn__Name Is Nothing)
        End Function
        Public Sub ResetName()
            __pbn__Name = Nothing
        End Sub
        Private __pbn__Name As String

        <Global.ProtoBuf.ProtoMember(2, Name:="location")>
        <Global.System.ComponentModel.DefaultValue("")>
        Public Property Location As String
            Get
                Return If(__pbn__Location, "")
            End Get
            Set(ByVal value As String)
                __pbn__Location = value
            End Set
        End Property
        Public Function ShouldSerializeLocation() As Boolean
            Return Not (__pbn__Location Is Nothing)
        End Function
        Public Sub ResetLocation()
            __pbn__Location = Nothing
        End Sub
        Private __pbn__Location As String

        <Global.ProtoBuf.ProtoMember(3)>
        Public Property sellPrice As UInteger
            Get
                Return __pbn__sellPrice.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__sellPrice = value
            End Set
        End Property
        Public Function ShouldSerializesellPrice() As Boolean
            Return Not (__pbn__sellPrice Is Nothing)
        End Function
        Public Sub ResetsellPrice()
            __pbn__sellPrice = Nothing
        End Sub
        Private __pbn__sellPrice As UInteger?

        <Global.ProtoBuf.ProtoMember(4)>
        Public Property buyPrice As UInteger
            Get
                Return __pbn__buyPrice.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__buyPrice = value
            End Set
        End Property
        Public Function ShouldSerializebuyPrice() As Boolean
            Return Not (__pbn__buyPrice Is Nothing)
        End Function
        Public Sub ResetbuyPrice()
            __pbn__buyPrice = Nothing
        End Sub
        Private __pbn__buyPrice As UInteger?

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class AppearanceFlagChangedToExpire
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1)>
        Public Property formerObjectTypeId As UInteger
            Get
                Return __pbn__formerObjectTypeId.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__formerObjectTypeId = value
            End Set
        End Property
        Public Function ShouldSerializeformerObjectTypeId() As Boolean
            Return Not (__pbn__formerObjectTypeId Is Nothing)
        End Function
        Public Sub ResetformerObjectTypeId()
            __pbn__formerObjectTypeId = Nothing
        End Sub
        Private __pbn__formerObjectTypeId As UInteger?

    End Class

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class AppearanceFlagCyclopedia
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1)>
        Public Property cyclopediaType As UInteger
            Get
                Return __pbn__cyclopediaType.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__cyclopediaType = value
            End Set
        End Property
        Public Function ShouldSerializecyclopediaType() As Boolean
            Return Not (__pbn__cyclopediaType Is Nothing)
        End Function
        Public Sub ResetcyclopediaType()
            __pbn__cyclopediaType = Nothing
        End Sub
        Private __pbn__cyclopediaType As UInteger?

    End Class

End Class

<Global.ProtoBuf.ProtoContract()>
Partial Public Class FrameGroup
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, IsRequired:=True)>
    Public Property fixedFrameGroup As UInteger

    <Global.ProtoBuf.ProtoMember(2, Name:="id", IsRequired:=True)>
    Public Property Id As UInteger

    <Global.ProtoBuf.ProtoMember(3, Name:="spriteInfo", IsRequired:=True)>
    Public Property spriteInfoValue As SpriteInfo

    <Global.ProtoBuf.ProtoContract()>
    Partial Public Class SpriteInfo
        Implements Global.ProtoBuf.IExtensible

        Private __pbn__extensionData As Global.ProtoBuf.IExtension

        Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
            Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
        End Function

        <Global.ProtoBuf.ProtoMember(1, IsRequired:=True)>
        Public Property patternX As UInteger

        <Global.ProtoBuf.ProtoMember(2, IsRequired:=True)>
        Public Property patternY As UInteger

        <Global.ProtoBuf.ProtoMember(3, IsRequired:=True)>
        Public Property patternZ As UInteger

        <Global.ProtoBuf.ProtoMember(4, Name:="layers", IsRequired:=True)>
        Public Property Layers As UInteger

        <Global.ProtoBuf.ProtoMember(5)>
        Public Property spriteIDs As UInteger()

        <Global.ProtoBuf.ProtoMember(6, Name:="animations")>
        Public ReadOnly Property Animations As New Global.System.Collections.Generic.List(Of SpriteAnimation)

        <Global.ProtoBuf.ProtoMember(7)>
        Public Property cropSize As UInteger
            Get
                Return __pbn__cropSize.GetValueOrDefault()
            End Get
            Set(ByVal value As UInteger)
                __pbn__cropSize = value
            End Set
        End Property
        Public Function ShouldSerializecropSize() As Boolean
            Return Not (__pbn__cropSize Is Nothing)
        End Function
        Public Sub ResetcropSize()
            __pbn__cropSize = Nothing
        End Sub
        Private __pbn__cropSize As UInteger?

        <Global.ProtoBuf.ProtoMember(8)>
        Public Property isOpaque As Boolean
            Get
                Return __pbn__isOpaque.GetValueOrDefault()
            End Get
            Set(ByVal value As Boolean)
                __pbn__isOpaque = value
            End Set
        End Property
        Public Function ShouldSerializeisOpaque() As Boolean
            Return Not (__pbn__isOpaque Is Nothing)
        End Function
        Public Sub ResetisOpaque()
            __pbn__isOpaque = Nothing
        End Sub
        Private __pbn__isOpaque As Boolean?

        <Global.ProtoBuf.ProtoMember(9, Name:="size")>
        Public Property SizeValue As Size

        <Global.ProtoBuf.ProtoContract()>
        Partial Public Class SpriteAnimation
            Implements Global.ProtoBuf.IExtensible

            Private __pbn__extensionData As Global.ProtoBuf.IExtension

            Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
                Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
            End Function

            <Global.ProtoBuf.ProtoMember(1)>
            Public Property startPhase As UInteger
                Get
                    Return __pbn__startPhase.GetValueOrDefault()
                End Get
                Set(ByVal value As UInteger)
                    __pbn__startPhase = value
                End Set
            End Property
            Public Function ShouldSerializestartPhase() As Boolean
                Return Not (__pbn__startPhase Is Nothing)
            End Function
            Public Sub ResetstartPhase()
                __pbn__startPhase = Nothing
            End Sub
            Private __pbn__startPhase As UInteger?

            <Global.ProtoBuf.ProtoMember(2, Name:="synced")>
            Public Property Synced As Boolean
                Get
                    Return __pbn__Synced.GetValueOrDefault()
                End Get
                Set(ByVal value As Boolean)
                    __pbn__Synced = value
                End Set
            End Property
            Public Function ShouldSerializeSynced() As Boolean
                Return Not (__pbn__Synced Is Nothing)
            End Function
            Public Sub ResetSynced()
                __pbn__Synced = Nothing
            End Sub
            Private __pbn__Synced As Boolean?

            <Global.ProtoBuf.ProtoMember(3)>
            <Global.System.ComponentModel.DefaultValue(False)>
            Public Property randomStartPhase As Boolean
                Get
                    Return If(__pbn__randomStartPhase, False)
                End Get
                Set(ByVal value As Boolean)
                    __pbn__randomStartPhase = value
                End Set
            End Property
            Public Function ShouldSerializerandomStartPhase() As Boolean
                Return Not (__pbn__randomStartPhase Is Nothing)
            End Function
            Public Sub ResetrandomStartPhase()
                __pbn__randomStartPhase = Nothing
            End Sub
            Private __pbn__randomStartPhase As Boolean?

            <Global.ProtoBuf.ProtoMember(4, IsRequired:=True)>
            Public Property loopType As AnimationLoopType = AnimationLoopType.AnimationLoopTypePingpong

            <Global.ProtoBuf.ProtoMember(5)>
            Public Property loopCount As UInteger
                Get
                    Return __pbn__loopCount.GetValueOrDefault()
                End Get
                Set(ByVal value As UInteger)
                    __pbn__loopCount = value
                End Set
            End Property
            Public Function ShouldSerializeloopCount() As Boolean
                Return Not (__pbn__loopCount Is Nothing)
            End Function
            Public Sub ResetloopCount()
                __pbn__loopCount = Nothing
            End Sub
            Private __pbn__loopCount As UInteger?

            <Global.ProtoBuf.ProtoMember(6, Name:="phases")>
            Public ReadOnly Property Phases As New Global.System.Collections.Generic.List(Of SpritePhase)

            <Global.ProtoBuf.ProtoContract()>
            Partial Public Class SpritePhase
                Implements Global.ProtoBuf.IExtensible

                Private __pbn__extensionData As Global.ProtoBuf.IExtension

                Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
                    Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
                End Function

                <Global.ProtoBuf.ProtoMember(1, IsRequired:=True)>
                Public Property minDuration As UInteger

                <Global.ProtoBuf.ProtoMember(2, IsRequired:=True)>
                Public Property maxDuration As UInteger

            End Class

            <Global.ProtoBuf.ProtoContract(Name:="ANIMATION_LOOP_TYPE")>
            Public Enum AnimationLoopType
                <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_PINGPONG")>
                AnimationLoopTypePingpong = -1
                <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_INFINITE")>
                AnimationLoopTypeInfinite = 0
                <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_COUNTED")>
                AnimationLoopTypeCounted = 1
            End Enum

        End Class

        <Global.ProtoBuf.ProtoContract()>
        Partial Public Class Size
            Implements Global.ProtoBuf.IExtensible

            Private __pbn__extensionData As Global.ProtoBuf.IExtension

            Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
                Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
            End Function

            <Global.ProtoBuf.ProtoMember(1, Name:="width", IsRequired:=True)>
            Public Property Width As UInteger

            <Global.ProtoBuf.ProtoMember(2, Name:="height", IsRequired:=True)>
            Public Property Height As UInteger

        End Class

    End Class

End Class

<Global.ProtoBuf.ProtoContract()>
Partial Public Class Appearance
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, IsRequired:=True)>
    Public Property clientID As UInteger

    <Global.ProtoBuf.ProtoMember(2)>
    Public ReadOnly Property frameGroups As New Global.System.Collections.Generic.List(Of FrameGroup)

    <Global.ProtoBuf.ProtoMember(3, Name:="attributes", IsRequired:=True)>
    Public Property Attributes As Attributes

End Class

<Global.ProtoBuf.ProtoContract()>
Partial Public Class DatFile
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name:="objects")>
    Public ReadOnly Property Objects As New Global.System.Collections.Generic.List(Of Appearance)

    <Global.ProtoBuf.ProtoMember(2, Name:="outfits")>
    Public ReadOnly Property Outfits As New Global.System.Collections.Generic.List(Of Appearance)

    <Global.ProtoBuf.ProtoMember(3, Name:="effects")>
    Public ReadOnly Property Effects As New Global.System.Collections.Generic.List(Of Appearance)

    <Global.ProtoBuf.ProtoMember(4, Name:="missiles")>
    Public ReadOnly Property Missiles As New Global.System.Collections.Generic.List(Of Appearance)

End Class

<Global.ProtoBuf.ProtoContract(Name:="PLAYER_ACTION")>
Public Enum PlayerAction
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_NONE")>
    PlayerActionNone = 0
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_LOOK")>
    PlayerActionLook = 1
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_USE")>
    PlayerActionUse = 2
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_OPEN")>
    PlayerActionOpen = 3
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_ACTION_AUTOWALK_HIGHLIGHT")>
    PlayerActionAutowalkHighlight = 4
End Enum

<Global.ProtoBuf.ProtoContract(Name:="ITEM_CATEGORY")>
Public Enum ItemCategory
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_ARMORS")>
    ItemCategoryArmors = 1
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_AMULETS")>
    ItemCategoryAmulets = 2
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_BOOTS")>
    ItemCategoryBoots = 3
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_CONTAINERS")>
    ItemCategoryContainers = 4
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_DECORATION")>
    ItemCategoryDecoration = 5
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_FOOD")>
    ItemCategoryFood = 6
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_HELMETS_HATS")>
    ItemCategoryHelmetsHats = 7
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_LEGS")>
    ItemCategoryLegs = 8
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_OTHERS")>
    ItemCategoryOthers = 9
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_POTIONS")>
    ItemCategoryPotions = 10
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_RINGS")>
    ItemCategoryRings = 11
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_RUNES")>
    ItemCategoryRunes = 12
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_SHIELDS")>
    ItemCategoryShields = 13
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_TOOLS")>
    ItemCategoryTools = 14
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_VALUABLES")>
    ItemCategoryValuables = 15
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_AMMUNITION")>
    ItemCategoryAmmunition = 16
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_AXES")>
    ItemCategoryAxes = 17
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_CLUBS")>
    ItemCategoryClubs = 18
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_DISTANCE_WEAPONS")>
    ItemCategoryDistanceWeapons = 19
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_SWORDS")>
    ItemCategorySwords = 20
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_WANDS_RODS")>
    ItemCategoryWandsRods = 21
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_PREMIUM_SCROLLS")>
    ItemCategoryPremiumScrolls = 22
    <Global.ProtoBuf.ProtoEnum(Name:="ITEM_CATEGORY_TIBIA_COINS")>
    ItemCategoryTibiaCoins = 23
End Enum

<Global.ProtoBuf.ProtoContract(Name:="PLAYER_PROFESSION")>
Public Enum PlayerProfession
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_ANY")>
    PlayerProfessionAny = -1
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_NONE")>
    PlayerProfessionNone = 0
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_KNIGHT")>
    PlayerProfessionKnight = 1
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_PALADIN")>
    PlayerProfessionPaladin = 2
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_SORCERER")>
    PlayerProfessionSorcerer = 3
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_DRUID")>
    PlayerProfessionDruid = 4
    <Global.ProtoBuf.ProtoEnum(Name:="PLAYER_PROFESSION_PROMOTED")>
    PlayerProfessionPromoted = 10
End Enum

<Global.ProtoBuf.ProtoContract(Name:="ANIMATION_LOOP_TYPE")>
Public Enum AnimationLoopType
    <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_PINGPONG")>
    AnimationLoopTypePingpong = -1
    <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_INFINITE")>
    AnimationLoopTypeInfinite = 0
    <Global.ProtoBuf.ProtoEnum(Name:="ANIMATION_LOOP_TYPE_COUNTED")>
    AnimationLoopTypeCounted = 1
End Enum

<Global.ProtoBuf.ProtoContract(Name:="HOOK_TYPE")>
Public Enum HookType
    <Global.ProtoBuf.ProtoEnum(Name:="HOOK_TYPE_SOUTH")>
    HookTypeSouth = 1
    <Global.ProtoBuf.ProtoEnum(Name:="HOOK_TYPE_EAST")>
    HookTypeEast = 2
End Enum
Class Datfiles

    'saving/loading
    Public Sub Writefile(filename As String)
        Dim fs As FileStream = File.Create(filename)
        ''option 1
        'Dim objData As Appearance = New Appearance With {.ClientID = "blahblahblah"}
        'Serializer.Serialize(fs, objData) 'saving

        ''option 2
        'Dim objData1 As DatProto = New DatProto()
        'Serializer.Serialize(fs, objData1)
    End Sub
    Public Function Readfile(filename As String) As DatFile
        Dim fs As FileStream = File.Open(filename, FileMode.Open)
        Dim objData1 As DatFile = Serializer.Deserialize(Of DatFile)(fs) 'loading
        Return objData1
    End Function

End Class
#Enable Warning BC40008, BC40055, IDE1006
